name: Artifact This repo
on:
 push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: nnsbghac
          path: ./
          retention-days: 10
